dist: trusty
language: python

branches:
    only:
        - master
env:
  global:
    secure: QR5J++MXHupeT32YxnWp0QcLarY5aSvZuYA8EU0l7ObQo+732E0p+LROYOmkPgHgiEEOgk+f8QMfc2/wlakpSkcVo7qOzsqzIaL8VFxllnIBmkJg65sMmhnsseVWewxCRjXJHeoOnICw3MbApDpYr6xlpMePRLN8X3p/ZL3XhXstbBGNXhYP81sqVafBMNE6IQ9uhbqcY8Kqbu/M1gfz0UpG70jqfipX4f8CJNh0fVz6zfPjTp7eRe0trAUwUw3GaTllOAUCU/g2RZ+re+M7cx6BpKeFQVuRTBYGixofXQGa2f9NY4tqZwzKjD19oiyUjFFlijGdmrGyl5lSzaNMDL5R+Aynqkv684UupagSkPtWSY6jAkFCUHwaqc9hR08AmNd0poey/VSgAwpVC3KxF8TRSuJeUsHm9QuTx4ODwhBCpOitJy0SVZ0fwXbWmU6iKRotJW8WTxhx8ukvm+SCDLIpuP3xQWk5RLOQd3sK2pOtmQQ6mJ5nYfDzgr38m+E0tR/wPBcwxFmnbpImQfJizyJBi+baB0+RpwwWRKZuJKtvHFUxZzPZYRcaWRgkXXoU6immH4+6UKLw3jsB5cKIPQRDU6FYD6RWARgkuHcSTHXGdeWq7moX8rIRt0lslzGAroWYMGaoYli4n7/n9k8ZgT+3l2ZvgXCFVhii4bBQKGI=

matrix:
  include:
    - env: PYTHON=3.6
    - env: PYTHON=3.5

before_install:
  # install environment for dask_cudf
  - source ./travisci/install-env-dask_cudf.sh
  # install miniconda
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH

install:
  # check
  - conda --version
  # install conda build
  - conda install conda-build anaconda-client flake8 conda-verify --yes
script:
  # Activate root environment
  - source activate root
  # check conda versions
  - conda list
  # build dask_cudf
  - source ./travisci/build_dask_cudf.sh
  - flake8

after_success:
  - source ./travisci/upload-anaconda.sh
